name: Build docker file

on:
  push:
    branches: [ main ]
    paths: [AutoscalerApi/**, .github/workflows/AutoscalerApi.yml]
  pull_request:
    branches: [ main ]
    paths: [AutoscalerApi/**, .github/workflows/AutoscalerApi.yml]

env:
  DOTNET_VERSION: '6.0.x'

jobs:
  build:
    runs-on: self-hosted
    env:
      image: docker.io/ofcoursedude/moje:autoscaler-${{ github.RUN_ID }}
    steps:
      - uses: actions/checkout@v3
      - name: Build the Docker image
        run: docker build . --file AutoscalerApi/Dockerfile -t ${{env.image}}
      - name: Docker Login
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v1.14.1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Docker push
        run: docker push ${{env.image}}
        if: github.ref == 'refs/heads/main'
#      - name: Docker cleanup
#        run: docker image prune -f

  create-binary:
   runs-on: self-hosted
   steps:
     - uses: actions/checkout@v3
     - name: Setup DotNet ${{ env.DOTNET_VERSION }} Environment
       uses: actions/setup-dotnet@v2
       with:
         dotnet-version: ${{ env.DOTNET_VERSION }}
     - name: Publish package
       run: dotnet publish AutoscalerApi --self-contained -p:PublishSingleFile=true -p:PublishTrimmed=true -r linux-x64 -c Release -o artifacts
     - name: Publish artifacts
       if: github.ref == 'refs/heads/main'
       uses: actions/upload-artifact@v3.0.0
       with:
         name: github-autoscaler-linux-amd64
         path: artifacts/*
         retention-days: 1