name: Build full solution

on:
  push:
  workflow_dispatch:

jobs:
  build-solution:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Build solution
        #uses: mosteo-actions/docker-run@v1
        uses: addnab/docker-run-action@v3
        with:
          image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
          command: dotnet build

  create-binary:
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    strategy:
      matrix: 
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v3
      - name: Publish package
        uses: mosteo-actions/docker-run@v1
        with:
          image: mcr.microsoft.com/dotnet/sdk:6.0-alpine
          command: dotnet publish AutoscalerApi --self-contained -p:PublishSingleFile=true -p:PublishReadyToRun=true -p:PublishTrimmed=true -r linux-${{ matrix.arch }} -c Release -o artifacts
      - name: Publish artifacts
        # if: github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v3.0.0
        with:
          name: github-autoscaler-linux-${{ matrix.arch }}
          path: artifacts/*
          retention-days: 1
