name: Build branch

on:
  push:
    branches-ignore: 
    - main
  workflow_dispatch:

jobs:
  build-branch:
    runs-on: self-hosted
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v2
      - name: Build with Docker
        # You may pin to the exact commit or the version.
        # uses: addnab/docker-run-action@4f65fabd2431ebc8d299f8e5a018d79a769ae185
        uses: addnab/docker-run-action@v3
        with:
          # Image
          image: mcr.microsoft.com/dotnet/sdk:6.0
          options: -v ${{ github.workspace }}:/source -w /source
          # Run command in container
          run: dotnet build

