name: Build docker file

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file AutoscalerApi\Dockerfile --tag ofcoursedude/moje:autoscaler
