name: Build Multiscaler - docker BuildX

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  multiarch-build:
    runs-on: self-hosted
    env:
      image: docker.io/ofcoursedude/moje:multiscaler-${{ github.RUN_ID }}
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v3
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: AutoscalerApi/Dockerfile
          pull: true
          push: true
          tags: ${{env.image}}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
